### ISSUE TITLE
Create Controllers and Middleware for the Application

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#10]
Attach Controllers and Middleware to the Application. 

1. Add it to the App folder > Create new Folder > Then place (Controllers and Middleware).
2. Work together while uploading.
3. Do it asap.  

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200218483765434) by [Unito](https://www.unito.io/learn-more)

**Comment by MuhammadAffanUsmani** [comment]
On it, EFFECTIVE IMMEDIATELY.

**Comment by Muhammad-Hassan-Farooq** [comment]
Task complete. 
Successfully added the controllers and middleware for this application.
Contributors - Back-end-Developers 
@Muhammad-Hassan-Farooq 
@MuhammadAffanUsmani 

![image](https://user-images.githubusercontent.com/81969481/115318741-cc05d500-a197-11eb-86d6-716e5a83a149.png)
