### ISSUE TITLE
Add Models to the Application.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#13]
Create and Add Models to the application.

1. Place it in the App folder > Create new Folder > Place Models (At-least) 2 Models 
1. Do it Asap.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200218957044308) by [Unito](https://www.unito.io/learn-more)

**Comment by MuhammadAffanUsmani** [comment]
Issue tested, all set.

**Comment by Muhammad-Hassan-Farooq** [comment]
#13 Added Models to the App folder reviewed and tested. 

![image](https://user-images.githubusercontent.com/81969481/115321953-6c5ef800-a19e-11eb-98ea-f3e821b5ab01.png)
