### ISSUE TITLE
Add Providers to the Application

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#15]
Add providers to the application in the 

1. App folder > Create new folder > Providers .
1. Please do it Asap

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200219052123939) by [Unito](https://www.unito.io/learn-more)

**Comment by MuhammadAffanUsmani** [comment]
I will be adding EFFECTIVE IMMEDIATELY.

**Comment by MuhammadAffanUsmani** [comment]
Task Completed. 
Added Providers, reviewed and checked.

![image](https://user-images.githubusercontent.com/81906984/115324123-2d995580-a13e-11eb-993d-922ae3e7145a.png)
