### ISSUE TITLE
Create Link of App

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#18]
Addition of App linkage file.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200224410625034) by [Unito](https://www.unito.io/learn-more)

**Comment by mihadmiko** [comment]
On it.

**Comment by mihadmiko** [comment]
Done and merged 

![image](https://user-images.githubusercontent.com/82386440/115464668-46f3dd80-a1e2-11eb-9a17-ea0d8e09c94c.png)
