### ISSUE TITLE
Create Cache of the Linked-Folder

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#20]
Add cache files

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200224547611659) by [Unito](https://www.unito.io/learn-more)

**Comment by mihadmiko** [comment]
I have already created and added them to the folder #18 

![image](https://user-images.githubusercontent.com/82386440/115464606-2e83c300-a1e2-11eb-84ed-9e46cf949667.png)
