### ISSUE TITLE
Create Configuration Files.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#21]
Addition of configuration files. (Config files)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200224583736543) by [Unito](https://www.unito.io/learn-more)

**Comment by Muhammad-Hassan-Farooq** [comment]
Working on it.

**Comment by MuhammadAffanUsmani** [comment]
Working on it.

**Comment by Muhammad-Hassan-Farooq** [comment]
All Done.

![image](https://user-images.githubusercontent.com/81969481/115467824-8f93b100-a24b-11eb-9f16-6b80edc5ef73.png)
