### ISSUE TITLE
Addition of Database Programs

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#23]
Add the Database folder to Main

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200224668962756) by [Unito](https://www.unito.io/learn-more)

**Comment by MuhammadAffanUsmani** [comment]
Roger. Creating a new stream as the Database-Stream.

**Comment by MuhammadAffanUsmani** [comment]
Created a new Stream as Database-Stream and also created a new folder for it Main > Database > Factories.

![image](https://user-images.githubusercontent.com/81906984/115469144-f2079580-a1e8-11eb-89fb-85b02cd23e74.png)

**Comment by MuhammadAffanUsmani** [comment]
Gonna create the folder again as the pervious caused error in addition to files. Gonna add database folder in this task #24

**Comment by Muhammad-Hassan-Farooq** [comment]
Ok noted. Please be careful.

**Comment by MuhammadAffanUsmani** [comment]
Made Changes created the database folder in Main > Database and also added factory in Main > Database > Factories > UserFactory.php #24 

![image](https://user-images.githubusercontent.com/81906984/115470347-0351a180-a1eb-11eb-8562-29087dbcd478.png)
