### ISSUE TITLE
Add Factories to Database folder.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#24]
Add the factories to the Database folder as > New folder > Factories

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200224629101665) by [Unito](https://www.unito.io/learn-more)

**Comment by MuhammadAffanUsmani** [comment]
Adding the Factories soon.
