### ISSUE TITLE
Add Migrations to Database folder.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#27]
Add the migration folder to the Database folder.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200227210409147) by [Unito](https://www.unito.io/learn-more)

**Comment by mihadmiko** [comment]
Worked on it added the migrations to the Database folder in Main > Database > Migrations > (Files placed here).
 Please review and allow to merge 

![image](https://user-images.githubusercontent.com/82386440/115550368-6fe3a380-a2b2-11eb-8078-96fda507c71e.png)

**Comment by Muhammad-Hassan-Farooq** [comment]
Good work you may create a pull request and I will review the files there.

**Comment by mihadmiko** [comment]
#28 
![image](https://user-images.githubusercontent.com/82386440/115551641-08c6ee80-a2b4-11eb-839e-bea0fb3aefa4.png)
