### ISSUE TITLE
Add Seeders to Database folder.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#29]
Addition of Seeders to the database folder.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200227480708565) by [Unito](https://www.unito.io/learn-more)

**Comment by mihadmiko** [comment]
Added Seeder program file . 
![image](https://user-images.githubusercontent.com/82386440/115553854-8d1a7100-a2b6-11eb-90e8-9f8db201822a.png)

**Comment by Muhammad-Hassan-Farooq** [comment]
There has been a mistake you have added the seeder file from the main which is restricted until revision, please add it from the Database-Stream. 

mean while I will delete the file from the main stream.

**Comment by mihadmiko** [comment]
ok work on it

**Comment by mihadmiko** [comment]
Correction 
![image](https://user-images.githubusercontent.com/82386440/115554921-a53ec000-a2b7-11eb-878c-366b32627c97.png)

**Comment by mihadmiko** [comment]
Addition success.
![image](https://user-images.githubusercontent.com/82386440/115555559-52b1d380-a2b8-11eb-8f9c-9ec892d2751a.png)
#28
