### ISSUE TITLE
Add gitignore file to Database Folder

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#31]
Add .gitignore extension to the Database folder.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200227529240481) by [Unito](https://www.unito.io/learn-more)

**Comment by mihadmiko** [comment]
done 
![image](https://user-images.githubusercontent.com/82386440/115557341-49c20180-a2ba-11eb-95c6-104f3e9c2504.png)

**Comment by mihadmiko** [comment]
done #32
