### ISSUE TITLE
Daily Stand-up Meeting

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#34]
This meeting consisted all the Developers and the Team leader it was on discussion of releasing the (Alpha -v) of our project.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200234805054999) by [Unito](https://www.unito.io/learn-more)

**Comment by Muhammad-Hassan-Farooq** [comment]
Details of Meeting
<img width="1440" alt="Screenshot 2021-04-22 at 9 21 27 PM" src="https://user-images.githubusercontent.com/81969481/115751172-5b86d000-a3b2-11eb-8d8b-15c62142cdb4.png">

**Comment by Marc-Nyembo** [comment]
The meeting was a success, all core-objectives were discussed with all the team members present.
![Capture](https://user-images.githubusercontent.com/80329340/115751267-b106b100-a3a1-11eb-9651-185aac06acf9.PNG)
