### ISSUE TITLE
Create Public Config Program files

### ISSUE THREAD

**Issue by mihadmiko** [Muhammad-Hassan-Farooq/SE-Project-repo#35]
Please add htaccess and add Favicon extension.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200241328402394) by [Unito](https://www.unito.io/learn-more)

**Comment by mihadmiko** [comment]
ok i will do it now

**Comment by mihadmiko** [comment]
![image](https://user-images.githubusercontent.com/82386440/115932233-34ed9580-a495-11eb-91a5-b41524e73af0.png)
 done and merge.

**Comment by Muhammad-Hassan-Farooq** [comment]
The .ico tag is missing for the favicon.ico.

I will be fixing this from the Main-Stream.

 - Will be avoided from next time.

**Comment by Muhammad-Hassan-Farooq** [comment]
Will create a new issue and resolve it by @Muhammad-Hassan-Farooq
