### ISSUE TITLE
Add index.php in Public folder.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#37]
Add the index.php files in the public folder.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200241395775229) by [Unito](https://www.unito.io/learn-more)

**Comment by mihadmiko** [comment]
on it

**Comment by mihadmiko** [comment]
index file is added.
![image](https://user-images.githubusercontent.com/82386440/115933123-e9d48200-a496-11eb-9a08-21c70b5a8cf9.png)
