### ISSUE TITLE
Addition of rob and webconfig

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#39]
Add the robot & web config program files to the public folder.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200241406195692) by [Unito](https://www.unito.io/learn-more)

**Comment by mihadmiko** [comment]
![image](https://user-images.githubusercontent.com/82386440/115933922-9a8f5100-a498-11eb-8bae-bfeef97ca58e.png)
Done

**Comment by Muhammad-Hassan-Farooq** [comment]
webconfig is pending.

**Comment by mihadmiko** [comment]
![image](https://user-images.githubusercontent.com/82386440/115934227-37ea8500-a499-11eb-9a6e-da821ebc8d9a.png)
now all done

**Comment by Muhammad-Hassan-Farooq** [comment]
Ok #39
