### ISSUE TITLE
Create/initiate a {php} application.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#4]
We are asked to create a JSON File reading application for student marks so please read out the details of project requirement and start with the first initiative of the [Back-end Developing].

* Note we have to make the application responsive and running.
* Provide us with the head-lead.
* Consider the requirements and come up with a program within (07:30 hrs) max. 
* Check your tasks on Asana board as well organise them efficiently.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200214886940800) by [Unito](https://www.unito.io/learn-more)

**Comment by MuhammadAffanUsmani** [comment]
progressing through!

**Comment by Muhammad-Hassan-Farooq** [comment]
I have uploaded the Application's first file in the App folder > Console > [Kernel.php)

![image](https://user-images.githubusercontent.com/81969481/115304135-019dc480-a17e-11eb-8b9b-cfbec2b3fda4.png)
