### ISSUE TITLE
Create Resources & add CSS.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#46]
Create a Resources folder and add CSS file to it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200242176313941) by [Unito](https://www.unito.io/learn-more)

**Comment by Marc-Nyembo** [comment]
Working on it!

**Comment by Marc-Nyembo** [comment]
![image](https://user-images.githubusercontent.com/80329340/115956698-f7c1eb80-a506-11eb-8ac4-39e104edd2ce.png)
Done #48
