### ISSUE TITLE
Add JS for Resources.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#49]
Add the js files

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200242134511059) by [Unito](https://www.unito.io/learn-more)

**Comment by Marc-Nyembo** [comment]
Working on it!

**Comment by Marc-Nyembo** [comment]
![image](https://user-images.githubusercontent.com/80329340/115957032-d9f58600-a508-11eb-805f-430585eee9b8.png)
Done #50
