### ISSUE TITLE
Add Language config to Resources.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#51]
Add lang files to the resources

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200242184812658) by [Unito](https://www.unito.io/learn-more)

**Comment by Marc-Nyembo** [comment]
Working on it.

**Comment by Marc-Nyembo** [comment]
![image](https://user-images.githubusercontent.com/80329340/115960193-b0dcf180-a518-11eb-9573-287ea15c51ae.png)
Done #52
