### ISSUE TITLE
Add Views to Resources - home page.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#53]
Add beta home page first

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200242271599891) by [Unito](https://www.unito.io/learn-more)

**Comment by Marc-Nyembo** [comment]
Working on it.

**Comment by Marc-Nyembo** [comment]
![image](https://user-images.githubusercontent.com/80329340/115960692-8d677600-a51b-11eb-8bf5-c87d7e33a890.png)
Done #56
