### ISSUE TITLE
Add show page to Views-Resources.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#54]
Add Views beta page

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200242271833591) by [Unito](https://www.unito.io/learn-more)

**Comment by Marc-Nyembo** [comment]
Working on it.

**Comment by Marc-Nyembo** [comment]
![image](https://user-images.githubusercontent.com/80329340/115960972-f7344f80-a51c-11eb-967a-9cb216bf0193.png)
Done #57
