### ISSUE TITLE
Add welcome page to Views-Resources.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#55]
Add welcome beta page

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200242303614765) by [Unito](https://www.unito.io/learn-more)

**Comment by Marc-Nyembo** [comment]
Working on it.

**Comment by Marc-Nyembo** [comment]
![image](https://user-images.githubusercontent.com/80329340/115961188-f7811a80-a51d-11eb-9af1-4389966f95a8.png)
Done #58
