### ISSUE TITLE
Create Routes + Add (api) for the App.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#59]
Create a Routes folder and (api) program file to it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200242684485418) by [Unito](https://www.unito.io/learn-more)

**Comment by mihadmiko** [comment]
Working on it.

**Comment by mihadmiko** [comment]
![image](https://user-images.githubusercontent.com/82386440/115972215-db6f8000-a501-11eb-9132-9676c5f00111.png)
Done and merged.
