### ISSUE TITLE
Create Channels for Routes. 

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#61]
Add the channels file program to the Routes.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200242775582669) by [Unito](https://www.unito.io/learn-more)

**Comment by mihadmiko** [comment]
on it.

**Comment by mihadmiko** [comment]
![image](https://user-images.githubusercontent.com/82386440/115972495-7ae14280-a503-11eb-9340-c3e7c092f33c.png)
Done and merged.
