### ISSUE TITLE
Add Console + Web File for the Resources.

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#63]
Add the console and the web files to Routes.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200242691212920) by [Unito](https://www.unito.io/learn-more)

**Comment by mihadmiko** [comment]
On it.

**Comment by mihadmiko** [comment]
![image](https://user-images.githubusercontent.com/82386440/115972620-4e79f600-a504-11eb-9313-903c00b7220d.png)
Done and merged.
