### ISSUE TITLE
Project Lookup Session(s)-2

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#65]
This meeting is set for the improvement of our project and also for discussing on releasing the Beta-version, as well as combined with the daily-standup-meeting.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200242819956622) by [Unito](https://www.unito.io/learn-more)

**Comment by MuhammadAffanUsmani** [comment]
Meeting screenshot, as it continues. 
<img width="1440" alt="Screenshot 2021-04-25 at 04 57 18" src="https://user-images.githubusercontent.com/81906984/115975980-d4d51d00-a582-11eb-89b3-22f543f80848.png">

**Comment by MuhammadAffanUsmani** [comment]
Beta version released. Issue resolved.
[OUR BETA VERSION.pdf](https://github.com/Muhammad-Hassan-Farooq/SE-Project-repo/files/6371034/OUR.BETA.VERSION.pdf)
<img width="1440" alt="Screenshot 2021-04-25 at 06 22 43" src="https://user-images.githubusercontent.com/81906984/115977187-25eb0e00-a58f-11eb-913f-21aceae06a89.png">
