### ISSUE TITLE
Create Handler for the Application

### ISSUE THREAD

**Issue by Muhammad-Hassan-Farooq** [Muhammad-Hassan-Farooq/SE-Project-repo#8]
Please create a (Handler) program file. 

1. Add it to the App folder > Create new Folder > Then place (Handler).
2. Please do it asap.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200179730969548/1200218432350266) by [Unito](https://www.unito.io/learn-more)

**Comment by MuhammadAffanUsmani** [comment]
I have added the handler file to the App folder > Exception > Handler.php and its merged.

![image](https://user-images.githubusercontent.com/81906984/115306976-6d9c1080-a11d-11eb-907f-5b17febc9a21.png)
